### ISSUE TITLE
GRAVITY RUSH™ [PCSA00011]

### ISSUE THREAD

**Issue by IllusionMan1212** [Vita3K/compatibility#177]
# Game summary
- Game name: GRAVITY RUSH™
- Game serial: PCSA00011
- Game version: 1.00

# Vita3K summary
- Version: v0.1
- Build number: 929
- Commit hash: https://github.com/vita3k/vita3k/commit/2a45507

# Test environment summary
- Tested by: IllusionMan1212
- OS: Windows 10 Pro
- CPU: AMD Ryzen 5 1600
- GPU: NVIDIA GTX 1050 Ti
- RAM: 8 GB

# Issues
Unicorn crash

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/3185394/vita3k.log)

**Comment by themikuik** [comment]
where did you download the file

**Comment by 203Null** [comment]
[vita3k.log](https://github.com/Vita3K/compatibility/files/6833621/vita3k.log)
Yellow screen atm.
![image](https://user-images.githubusercontent.com/19933093/126014209-83dd5a57-ad16-4ac8-8c7b-0e4f1e15968f.png)

**Comment by Zangetsu38** [comment]
works for me

**Comment by Snake2005sol** [comment]
GPU: AMD RX 5700 XT 8GB
CPU: AMD Ryzen 5 3600X
RAM: 12 GB

The game runs around 3-15 FPS with major graphical bugs, no audio
![иц4м5п](https://user-images.githubusercontent.com/90480248/132917264-3449651d-4cf7-4c72-8fb2-225a84aab27e.PNG)
![и35и3](https://user-images.githubusercontent.com/90480248/132917269-301346fd-39a7-4548-a877-c663994359f2.PNG)

**Comment by HoLored** [comment]
> Графический процессор: AMD RX 5700 XT 8 ГБ ЦП: AMD Ryzen 5 3600X Оперативная память: 12 ГБ
> 
> Игра работает со скоростью 3-15 кадров в секунду с серьезными графическими ошибками, без звука. ![иц4м5п](https://user-images.githubusercontent.com/90480248/132917264-3449651d-4cf7-4c72-8fb2-225a84aab27e.PNG) ![и35и3](https://user-images.githubusercontent.com/90480248/132917269-301346fd-39a7-4548-a877-c663994359f2.PNG)

Where did you download the game so that it starts at you tell me?

**Comment by Zangetsu38** [comment]
game have audio, just missing music

**Comment by HoLored** [comment]
> в игре есть звук, просто отсутствует музыка

Can you tell where you got the version that I started with a simple emulator crashes when adding a game

**Comment by HoLored** [comment]
> в игре есть звук, только музыки нет

Why do not you answer?

**Comment by exaltedb** [comment]
![unknown](https://user-images.githubusercontent.com/97992210/150236317-7a5cd412-bb77-43e2-b0eb-b30adc5f4263.png)

game locks up on this frame

Windows 11 Build 22000.434
GPU: AMD RX 580 8GB
CPU: AMD Ryzen 5 2600
RAM: 16 GB

**Comment by exaltedb** [comment]
![Untitled](https://user-images.githubusercontent.com/97992210/150236438-26ba9393-631d-46bb-b7a6-84401a23b11e.png)

game locks up on this frame

Windows 11 22000.434
GPU: AMD RX 580 8GB
CPU: AMD Ryzen 5 2600
RAM: 16 GB

**Comment by Zangetsu38** [comment]
> ![Untitled](https://user-images.githubusercontent.com/97992210/150236438-26ba9393-631d-46bb-b7a6-84401a23b11e.png)
> 
> game locks up on this frame
> 
> Windows 11 22000.434 GPU: AMD RX 580 8GB CPU: AMD Ryzen 5 2600 RAM: 16 GB

you can change console languague inside settings app
and probably rleate your gpu, normally here you see apple

**Comment by CesarHRS** [comment]
![Captura de tela 2022-11-03 222311](https://user-images.githubusercontent.com/73477344/199845949-48a1afe5-880e-45ab-8a5a-ba8d1870c74c.png)
![Captura de tela 2022-11-03 222400](https://user-images.githubusercontent.com/73477344/199845959-dbf0fbcf-c767-4566-8c6c-bfa46455b7c5.png)
![Captura de tela 2022-11-03 222420](https://user-images.githubusercontent.com/73477344/199845964-5f842e59-fc34-42f2-a965-d629a2756931.png)

Windows 11 21H2
GPU: RTX 3060-MaxQ 6GB 
CPU: i7 11800H
RAM: 16 GB

Using OpenGL

**Comment by fgfalll** [comment]
![capture_20221108184629993](https://user-images.githubusercontent.com/107929468/200626055-400cf484-e4b0-4e2a-9916-720e8f12e0a3.jpg)
![capture_20221108184642685](https://user-images.githubusercontent.com/107929468/200626064-a9eab21b-f79c-46f1-99fe-8593cab648cd.jpg)
![capture_20221108184308850](https://user-images.githubusercontent.com/107929468/200626065-ce7881fc-3c40-47a4-9b14-b5e762a4c8e4.jpg)

Works fine with vulkan but a lot of broken textures and shaders

Windows 11 22H2
Huawei matebook d14
CPU: Ruzen 7 3700U
GPU: Vega 8
RAM: 8GB

**Comment by johnledezma34** [comment]
This game works fine on steam deck using the emudeck installation. It has missing textures such as the missing apple in the beginning and missing textures all over that flash between bright odd colors. There’s one spot where the textures appear however right after meeting the dad but it only happened for a few seconds.

**Comment by CallMeJaydenn** [comment]
![image](https://user-images.githubusercontent.com/125328997/218620812-4a79013d-b518-4e2f-a0dc-be3ec1419c6d.png)
its been stuck on the loading screen for like, 10 minutes and idk what to do

**Comment by ManBear24** [comment]
![Screenshot_1408](https://user-images.githubusercontent.com/97818847/224753557-73490861-fc12-4381-b161-7f6b2ae96190.png)

With Vulkan I managed to get the game to actually fully load. No real missing textures, but do get a crash as soon as I hit the next cutscene.

Windows 11 22H2
CPU: Ryzen 5 5600X
GPU: GTX 1050TI
RAM: 32GB
API : Vulkan

**Comment by WeaselPC** [comment]
Same thing here, running on a Steam deck, with Vulkan. Able to reach the follow part just fine, but it "crashes" as soon as I reach after. It seems to be more of a softlock, cause sound still playing & I can hear the character footstep when I walk, which is interesting.

**Comment by brujo5** [comment]
Hello, sorry for the inconvenience but would someone be so kind as to share a save? after the intro it gets stuck on the loading screen

**Comment by ibmeto** [comment]
I have the same problem, any fixes please?

**Comment by SoaringGecko** [comment]
the current playable status of Gravity Rush is ingame, so it is probably not in a playable state

**Comment by ibmeto** [comment]
Maybe the Japanese version works?

**Comment by brujo5** [comment]
> Maybe the Japanese version works?

A few months ago someone shared a save file on discord that fixed that problem but they deleted the file and I can't find it anymore

**Comment by ArbestRiAgain** [comment]
The game goes further now
Recommended tags: Playable

**Comment by SoaringGecko** [comment]
> Recommended tags: Playable

How far though, because playable is classified as Games that can be played from start to finish with playable performance.

**Comment by ArbestRiAgain** [comment]
The scene where the game softlocks has been fixed and now game can be completed

**Comment by ibmeto** [comment]
Checked it out, it works now. Very glitchy sometimes and crashes near the start of chapter 2. Luckily it autosaves. Also it's almost unplayable on a integrated gpu. For my Samsung note 9, on opengl it's just a yellow screen, on vulcan it just crashes

**Comment by ArbestRiAgain** [comment]
I have a PC with a dedicated GPU, it works really well at a stable 30 FPS

**Comment by ArbestRiAgain** [comment]
> > Recommended tags: Playable
> 
> How far though, because playable is classified as Games that can be played from start to finish with playable performance.

It goes MUCH further, likely enough to complete the game.

**Comment by SoaringGecko** [comment]
For me the game seems to always crash after Kat names Dusty

**Comment by brujo5** [comment]
> The game goes further now Recommended tag: Playable

Sadly for android users we will have to wait for the V6 build I thought that with a save file this problem would be solved and we could play with the vita3k v5 version

**Comment by ArbestRiAgain** [comment]
Alright, once V6 with its code rebase and if I manage to complete the game with no frame drops, then it will be considered Playable.

**Comment by ibmeto** [comment]
New update fixed Gravity Rush but ruined Uncharted. Too many glitches to play either in opengl or vulcan

**Comment by ArbestRiAgain** [comment]
> New update fixed Gravity Rush but ruined Uncharted. Too many glitches to play either in opengl or vulcan on pc

Off-topic, Gravity Rush works fine but I know that Uncharted has those issues

**Comment by SoaringGecko** [comment]
> It goes MUCH further, likely enough to complete the game.

what OS are you using, what is your GPU, and what settings are you using in Vita3K because it crashes without fail on my PC.


> For me the game seems to always crash after Kat names Dusty
> 
> (On Windows 10 with a Radeon RX 580 Series when using either Vulcan or OpenGL)

**Comment by ArbestRiAgain** [comment]
This game is considered Playable

**Comment by SoaringGecko** [comment]
> This game is considered Playable

On your setup maybe but there are clearly still some big issues here, issues that are most likely caused by hardware, OS, or settings in the emulator. The emulator could have unique problems with this game depending on what OS you are running or who made your hardware (Nvidia, AMD, Intel, Apple, etc.) and it's drivers (maybe even specific models under a company could have unique problems). So it would be very helpful if you, a person that has a setup this game and emulator are not having any big conflicts/problems with would share this info. Just because it's playable on one PC does not mean it is on all PCs.

> > It goes MUCH further, likely enough to complete the game.
> 
> what OS are you using, what is your GPU, and what settings are you using in Vita3K because it crashes without fail on my PC.
> 
> > For me the game seems to always crash after Kat names Dusty
> > (On Windows 10 with a Radeon RX 580 Series when using either Vulcan or OpenGL)

**Comment by ArbestRiAgain** [comment]
On latest Vita3K build, there are MANY graphical improvements. The unimplemented sceGxm functions have been implemented now as well.

**Comment by SoaringGecko** [comment]
It didn't crash this time (I did have a crash when Kat spoke to Syd for the first time and questioned him about Raven but after relaunching the game it worked and got past that point. I will state here later how far I can get in the game but this may take me a little bit to test depending on far I can go)

**Comment by SoaringGecko** [comment]
Only problem I have noticed so far is after a while of playing the game it will visually freeze and stop taking inputs.

**Comment by ArbestRiAgain** [comment]
> Only problem I have noticed so far is after a while of playing the game it will visually freeze and stop taking inputs.

I don't have that problem with an NVIDIA

**Comment by othmanead** [comment]
> New update fixed Gravity Rush but ruined Uncharted. Too many glitches to play either in opengl or vulcan on pc

can you share screenshots of uncharted on the build without the issues and the current build?

**Comment by ibmeto** [comment]
Turns out that Uncharted works fine. I set it to render at 1080p, that caused the issue. Default resolution fixed the glitches

**Comment by RMED24** [comment]
I have been waiting for this day to arrive for the last 2-3 years, as this is a game I've been desperate to experience in a higher res (and no I don't own a PS4). I decided to check it out today and I'm glad it finally gets into game. Here's a screenshot of chapter 3:
![Screenshot_20230609_220047](https://github.com/Vita3K/compatibility/assets/81475204/eb404ea9-f3ae-4595-832c-c1ff8f72938e)

Man I don't believe this is real because this is the one game I've been waiting to play again from start to finish for years in a manner that doesn't feel cramped, and it somehow is real now. Thank you vita3k team and everyone involved to make this happen for this game and all other games that run on the emulator.

Since this is a compatibility report I suppose I should follow some sort of template.

OS: Nobara Linux 37
CPU: Ryzen 5 5600X
GPU: RX 6600 XT
RAM: 24GB
API : Vulkan

Game runs amazingly at 4x res and 8x anisotropic filtering with solid 30fps across the board (minus slight hitching from shader stutter and a random crash when going from chapter 2 and chapter 3 which wasn't consistent on my end)
I also noticed a slight over brightened bloom in the beginning, which seemed to be a tiny bit more than it's supposed to be. But maybe that's just because I've only seen the cutscene of the ps4 version in the last two years...

I cannot explain how happy I am to finally play this on PC after waiting multiple years. I was starting to lose hope and thought a PC port would come first :sweat_smile:

**Comment by petran79** [comment]
> It didn't crash this time (I did have a crash when Kat spoke to Syd for the first time and questioned him about Raven but after relaunching the game it worked and got past that point. I will state here later how far I can get in the game but this may take me a little bit to test depending on far I can go, how busy I end up being, and how much I play ToTK)

I did the same, pressing start to skip the sequence, but then game crashed right when Kat was ready to attack the tutorial monsters .
After reloading the emulator to play that scene again, both mouse and keyboard freeze with sound playing in the background and Windows needs a reboot. This happens everytime. 
if anyone can reproduce it with that save file.

https://www.mediafire.com/file/bp9csbovpbevi0d/PCSA00011.7z/file

**Comment by scriftty** [comment]
Hey at the beginning of the game when you talk to the policeman after saving him the game crashes and you have to reset you're savefile. I tried twice to play the cutscene and both times the game crashed.

**Comment by RetroDevPR** [comment]
Some glitchy animation on Kat when running and some slowdowns between cutscenes. Vita3K for Android (Release 7)

**Comment by jasonofthestorm** [comment]
Playing on Steam Deck with Vulkan. It crashed after I saved the kid in the beginning but I was able to continue after restarting. Now it's crashing consistently at the same spot, during the cutscene at the start of Chapter 2 after saving the policeman. Otherwise running great, really hope to see this in a fully playable state soon!

EDT: Was able to skip the cutscene and continue. Not ideal, but sweet!

**Comment by F1reFinger** [comment]
# Vita3K summary


- Version: v0.1.9
- Build number: 3341
- Commit hash: https://github.com/vita3k/vita3k/commit/04b47789
- CPU backend: Dynarmic
- GPU backend: Vulkan
- Ryzen 5 5600
- gtx1660 TI
- 16 gb ram 
![Captura de tela 2023-09-01 211904](https://github.com/Vita3K/compatibility/assets/78388335/9e39608d-e88f-4c95-8250-cc622856bb71)

**Comment by ocuffi** [comment]
> * Version: v0.1.9
> * Build number: 3341
> * Commit hash: [Vita3K/Vita3K@04b47789](https://github.com/Vita3K/Vita3K/commit/04b47789)
> * CPU backend: Dynarmic
> * GPU backend: Vulkan
> * Ryzen 5 5600
> * gtx1660 TI
> * 16 gb ram
>   ![Captura de tela 2023-09-01 211904](https://user-images.githubusercontent.com/78388335/265148901-9e39608d-e88f-4c95-8250-cc622856bb71.png)

i am facing the exact same problem on v0.1.9 build 3379

**Comment by xzi** [comment]
# Vita3K summary
- Version: v0.1.9
- Build number: 3443
- Commit hash: https://github.com/vita3k/vita3k/commit/6fa221cd
- CPU backend: Dynarmic
- GPU backend: Vulkan

Game crashes attempting to go through the episode 2 cutscene. No idea what could be causing this or how it works. Other than that the game appears to work fine with some wonky lighting. Error message and log are below.

[15:17:20.274] |C| [logging::init::<lambda_2>::operator ()]: Unhandled C++ exception. vk::Device::allocateDescriptorSets: ErrorOutOfPoolMemory

[vita3k.log](https://github.com/Vita3K/compatibility/files/13126315/vita3k.log)

**Comment by Kurosaki1514** [comment]
Game summary
Game name: GRAVITY RUSH™
Game serial: PCSA00011
Game version: 1.00

Vita3K summary
Version: v0.1.9
Build number: 3464


OS: Windows 10 Pro
CPU: I7 6700
GPU: NVIDIA GTX 1070
RAM: 16 GB

Issues
Sometimes it crashes when I name the cat Dusty, or when I chase the crow it also crashes and the Vita3K closes, and it also blinks sometimes
![Captura2222](https://github.com/Vita3K/compatibility/assets/148281596/38c2bf47-b195-4a1d-bffe-94945a348dae)

**Comment by Xxp0mxX** [comment]
Game summary
Game name: GRAVITY RUSH™
Game serial: PCSA00011
Game version: 1.00

Vita3K summary
Version: v0.1.9
Build number: 3464

OS: Manjaro KDE
CPU: 5600G
RAM: 16 GB ( 4 dedicated to APU )

Issues
Updated today, game crashed once and now shows the dialogue icons like this:
![Screenshot_20231103_172336](https://github.com/Vita3K/compatibility/assets/149835247/a0817678-2ef5-4111-acfe-10d5108c76c9)

Other than that, working normally

**Comment by Earleybyrd** [comment]
Game summary
Game name: GRAVITY RUSH™
Game serial: PCSA00011
Game version: 1.00

Vita3K summary
Version: v0.1.9
Build number: 3506 (i think?)

Steam Deck
Steam OS
Installed through Emudeck

Settings:
-CPU
Dynamic
-GPU
Vulkan
High Render Accuracy
Surface Sync enabled (fixes the excessive bloom)

A testament to how great this game’s art direction is (or how dumb I am) that it took me as long as it did to notice- but shadows have been completely f’ed, and I have no clue when this began. I’ve seen no discussion of this issue. Kat, NPCs, buildings- Nothing renders their shadows properly.

There’s always been strange lighting artifacting(?) that I’m pretty sure is a common issue, but I almost forgot Gravity Rush had shadows, and now I can see that, depending on the position of the camera, certain scenes will just be caked in massive, improperly-rendered shadows.

Comparison of a Vita screenshot, and Steam Deck

![DD887439-B68E-4F1B-8DBD-28D5B2BA61CB](https://github.com/Vita3K/compatibility/assets/127141355/1bcbfbf8-6a97-4e3a-a44d-f3ea5d150e8b)

![3DAE01E1-C668-4196-861A-75C1A82726FD](https://github.com/Vita3K/compatibility/assets/127141355/9ab10f24-8938-478d-8fe1-3a3284b408f0)

As far as I can tell, looking through older footage of the game running on Steam Deck, this wasn’t always an issue, and no matter how much I tweak my settings I can’t seem to fix it (Though I don’t put it past me to have missed something). Shadows only work on OpenGL, but the performance is too horrid + there’s a plethora of new, significantly worse lighting issues.

**Comment by Squareheron942** [comment]
Game summary

Game name: Gravity Rush
Game serial: PCSA00011
Game version: 1.00

Vita3k 0.1.9

macOS 13 (Ventura)

CPU: Ryzen 5 5600G
GPU: RX 580 8gb

Configuration:
Vulkan
Dynarmic
Accuracy: standard

Graphical glitches, between 3 and 7fps at all times (and causes the rest of the OS to run at the same FPS for some reason)
![image](https://github.com/Vita3K/compatibility/assets/82814680/54194005-3de2-415c-9016-47532f16d33e)

**Comment by nishinji** [comment]
![image](https://github.com/Vita3K/compatibility/assets/107111782/571e7718-a178-4f3d-ab6b-0cd9664db783)
i don't know about mac but maybe same path of vita3k i think

**Comment by Squareheron942** [comment]
> ![image](https://private-user-images.githubusercontent.com/107111782/289549758-571e7718-a178-4f3d-ab6b-0cd9664db783.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDE1NjUsIm5iZiI6MTcwMjMwMTI2NSwicGF0aCI6Ii8xMDcxMTE3ODIvMjg5NTQ5NzU4LTU3MWU3NzE4LWExNzgtNGYzZC1hYjZiLTBjZDk2NjRkYjc4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxMzI3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDBlODliZjMyN2UwYzcyZDY2YTNkZWUzNjRhNmE5NGExOWMzZTBlOGEzMmE4MDUyNzI3NTkzYmMxNzVmNjY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AkQx-RzBdnEHfF5nVlW_D9adiQaOUhN2V4X1_DsdhbM) i don't know about mac but maybe same path of vita3k I think

I needed to zip this as it's 60mb or so but this is the log
[vita3k.log.zip](https://github.com/Vita3K/compatibility/files/13641139/vita3k.log.zip)

**Comment by aryrk** [comment]
Game summary

Game name: Gravity Rush
Game serial: PCSA00011
Game version: 1.00

Vita3k 0.1.9

Android 13
Mediatek dimensity 8100-Ultra

Configuration:
Vulkan
Dynarmic
Accuracy: standard

No shadow all the time, overexposed in some parts

![Screenshot_2023-12-22-20-02-39-702_org vita3k emulator](https://github.com/Vita3K/compatibility/assets/74758565/5866efc1-1052-41ef-a234-931335129755)
![Screenshot_2023-12-22-19-57-42-695_org vita3k emulator](https://github.com/Vita3K/compatibility/assets/74758565/2600c9b6-2b9a-4990-93c3-3b592380a70e)

**Comment by 2FRAGGY** [comment]
Game summary
Game name: GRAVITY RUSH™
Game serial: PCSA00011
Game version: 1.00

Vita3K summary
Version: v0.1.9
Build number: 3524

Windows 10
CPU: Intel Core i3-9100F
RAM: 16GB
GPU: AMD Radeon RX 550 (4GB VRAM)
GPU Driver version: AMD Windows Driver Version 31.0.21905.1001

Settings:
-CPU
Dynarmic
-GPU
Vulkan Renderer
High Render Accuracy
Surface Sync enabled
FXAA
2x Resolution Upscaling
16x Anisotropic Filtering

No shadows anywhere as far as I can see, and occasional random stutters (not shader compilation related)
![image](https://github.com/Vita3K/compatibility/assets/154749860/dd090ee6-d573-4f98-8cc9-b6f449173a0b)

**Comment by retrofan2019** [comment]
last time I tested the game was a few months ago ..and yep the lighting and shadows were rendered properly ...so yea there is a regression on the vulkan backend ..and the performance on opengl is terrible and has more graphical issues but the lighting and shadows seem to work .. but although there is a regression the game itself is much more stable and rarely crashes ...hopefully it gets fixed soon .

**Comment by verbes4** [comment]
> Game summary Game name: GRAVITY RUSH™ Game serial: PCSA00011 Game version: 1.00
> 
> Vita3K summary Version: v0.1.9 Build number: 3506 (i think?)
> 
> Steam Deck Steam OS Installed through Emudeck
> 
> Settings: -CPU Dynamic -GPU Vulkan High Render Accuracy Surface Sync enabled (fixes the excessive bloom)
> 
> A testament to how great this game’s art direction is (or how dumb I am) that it took me as long as it did to notice- but shadows have been completely f’ed, and I have no clue when this began. I’ve seen no discussion of this issue. Kat, NPCs, buildings- Nothing renders their shadows properly.
> 
> There’s always been strange lighting artifacting(?) that I’m pretty sure is a common issue, but I almost forgot Gravity Rush had shadows, and now I can see that, depending on the position of the camera, certain scenes will just be caked in massive, improperly-rendered shadows.
> 
> Comparison of a Vita screenshot, and Steam Deck
> 
> ![DD887439-B68E-4F1B-8DBD-28D5B2BA61CB](https://private-user-images.githubusercontent.com/127141355/289338070-1bcbfbf8-6a97-4e3a-a44d-f3ea5d150e8b.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDYwNjUsIm5iZiI6MTcwNTUwNTc2NSwicGF0aCI6Ii8xMjcxNDEzNTUvMjg5MzM4MDcwLTFiY2JmYmY4LTZhOTctNGUzYS1hNDRkLWYzZWE1ZDE1MGU4Yi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTdUMTUzNjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmE1NWJkMjljMzI4YjMwZjg0ZjRlMDkxY2JlMjIyNjI3YWVlZDBiZDYzYTQ2ZDFhMjMzOTk1YzIwOWI5YmQ0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yNclzMDLIBOdBjcNUci-QGkGMWEwgj9Zkvj4w6wxwkQ)
> 
> ![3DAE01E1-C668-4196-861A-75C1A82726FD](https://private-user-images.githubusercontent.com/127141355/289338083-9ab10f24-8938-478d-8fe1-3a3284b408f0.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDYwNjUsIm5iZiI6MTcwNTUwNTc2NSwicGF0aCI6Ii8xMjcxNDEzNTUvMjg5MzM4MDgzLTlhYjEwZjI0LTg5MzgtNDc4ZC04ZmUxLTNhMzI4NGI0MDhmMC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTdUMTUzNjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmE1NTBiZDJmZDUwZTM0MTlhZGQ5MGQ3NTRkNWM3NmM4Yzk5ZTA3OGI3MmY1ZTE5ODNjNzljOTE0MDkzMDExOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8lDdC0ZB1va5mbLXIx0yvI1ZDdl-Nnn1pjEwhvqY6u8)
> 
> As far as I can tell, looking through older footage of the game running on Steam Deck, this wasn’t always an issue, and no matter how much I tweak my settings I can’t seem to fix it (Though I don’t put it past me to have missed something). Shadows only work on OpenGL, but the performance is too horrid + there’s a plethora of new, significantly worse lighting issues.

Same here, atleast the game is playable at all though lol
v0.2.0 3547-df70e4f5

**Comment by retrofan2019** [comment]
shadows fixed and lighting mostly fixed in the latest build

**Comment by hansschmucker** [comment]
At least on SteamDeck the issue reported in https://github.com/Vita3K/compatibility/issues/177#issuecomment-1722487473 still persists in 3570, meaning that the other world is very bright to the point that only shaded areas are actually visible.

**Comment by AbhayRodriguezGitHub** [comment]
Saben como solucionar estos errores graficos, Me aparece como compatibilidad jugable pero lo probe con todas las configuraciones posibles (Open GL, Vulka, Difrentes resoluciones, Y nada) 
![image](https://github.com/user-attachments/assets/36c4e7e8-99c4-42f8-9664-f5c79a0850a5)
![image](https://github.com/user-attachments/assets/ee1e0739-fbcb-4e79-8c9c-cdf99f461dea)

**Comment by BigBoss9989** [comment]
ryzen 7 5800x
Ram DDR4 8X4 32Gb 3600Hz
zotac rtx 3070 ti trinity oc 8gb
ASUS ROG Strix B550-F Gaming WiFi
![Screenshot 2024-09-15 160521](https://github.com/user-attachments/assets/09fa64ff-e623-447e-b131-3bc105234390)

hi or a problem I try to start the game gravity rush I open it then it loads infinitely I don't understand why then I checked the terminal alone this as red color |E| [export_sceGxmTextureInitSwizzled::<lambda_2>::operator ()]: sceGxmTextureInitSwizzled returned SCE_GXM_ERROR_INVALID_ALIGNMENT (0x805b0005)

**Comment by DummyAcc44** [comment]
Shadows flicker and spasm all over. Last build I have that works perfect is 3317

**Comment by cobra838** [comment]
> Shadows flicker and spasm all over
still flickering on 3674 =( 
[1.webm](https://github.com/user-attachments/assets/aa277e7b-158f-4110-a712-0adfa8e99502)

**Comment by Albert456** [comment]
Works great on Android Mali, Galaxy A34. Thank you.

**Comment by github-user1112** [comment]
# Vita3K summary
Version: v0.2.1
Build number: 4058
Commit hash: https://github.com/vita3k/vita3k/commit/6063154f
GPU backend: Vulkan

# Test environment summary
Tested by: gtihub-user
OS: Linux Mint 22.3
CPU: AMD Ryzen 5 5600
GPU: Radeon Rx 6600
RAM: 16 GB

# Issues
Still has vertex explosions quite often

# Screenshots

https://github.com/user-attachments/assets/1e9fa373-0051-4774-b2f3-90bc2755443f

# Log

[PCSA00011 - \[GRAVITY RUSH™\].log](https://github.com/user-attachments/files/29438487/PCSA00011.-.GRAVITY.RUSH.log)
 
# Recommended labels
